### ISSUE TITLE
Service 'org.kde.klipper' does not exist.

### ISSUE THREAD

**Issue by quancs** [larsks/lvcache#19]
(base) [sysadmin@cu05 lvcache-master]$ lvcache status -H data/data01
Service 'org.kde.klipper' does not exist.
Traceback (most recent call last):
  File "/sysadmin/miniconda3/bin/lvcache", line 33, in <module>
    sys.exit(load_entry_point('lvcache==1.0.1', 'console_scripts', 'lvcache')())
  File "/sysadmin/miniconda3/bin/lvcache", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/sysadmin/miniconda3/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/sysadmin/miniconda3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/sysadmin/miniconda3/lib/python3.8/site-packages/lvcache-1.0.1-py3.8.egg/lvcache/main.py", line 8, in <module>
  File "/sysadmin/miniconda3/lib/python3.8/site-packages/cliff-3.7.0-py3.8.egg/cliff/app.py", line 22, in <module>
    import cmd2
  File "/sysadmin/miniconda3/lib/python3.8/site-packages/cmd2-1.5.0-py3.8.egg/cmd2/__init__.py", line 30, in <module>
    from .cmd2 import Cmd
  File "/sysadmin/miniconda3/lib/python3.8/site-packages/cmd2-1.5.0-py3.8.egg/cmd2/cmd2.py", line 73, in <module>
    from .clipboard import (
  File "/sysadmin/miniconda3/lib/python3.8/site-packages/cmd2-1.5.0-py3.8.egg/cmd2/clipboard.py", line 14, in <module>
    _ = pyperclip.paste()
  File "/sysadmin/miniconda3/lib/python3.8/site-packages/pyperclip-1.8.2-py3.8.egg/pyperclip/__init__.py", line 681, in lazy_load_stub_paste
  File "/sysadmin/miniconda3/lib/python3.8/site-packages/pyperclip-1.8.2-py3.8.egg/pyperclip/__init__.py", line 301, in paste_klipper
AssertionError

**Comment by larsks** [comment]
This error doesn't have anything to do with this repository. You're getting some sort of error from the `pyperclip` module, which isn't used by this code.
