### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by vbence** [larsks/lvcache#5]
I'm not very familiar with python, so I just copy stuff from console:

Build seems OK:
```
# python setup.py build
running build
running build_py
creating build
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/lvcache
copying lvcache/lvm.py -> build/lib.linux-x86_64-2.7/lvcache
copying lvcache/cmd_status.py -> build/lib.linux-x86_64-2.7/lvcache
copying lvcache/cmd_remove.py -> build/lib.linux-x86_64-2.7/lvcache
copying lvcache/cmd_create.py -> build/lib.linux-x86_64-2.7/lvcache
copying lvcache/cmd_list.py -> build/lib.linux-x86_64-2.7/lvcache
copying lvcache/utils.py -> build/lib.linux-x86_64-2.7/lvcache
copying lvcache/__init__.py -> build/lib.linux-x86_64-2.7/lvcache
copying lvcache/main.py -> build/lib.linux-x86_64-2.7/lvcache
```

Installation says:
```
# python setup.py install
running install
running bdist_egg
running egg_info
creating lvcache.egg-info
writing requirements to lvcache.egg-info/requires.txt
writing lvcache.egg-info/PKG-INFO
writing top-level names to lvcache.egg-info/top_level.txt
writing dependency_links to lvcache.egg-info/dependency_links.txt
writing entry points to lvcache.egg-info/entry_points.txt
writing manifest file 'lvcache.egg-info/SOURCES.txt'
reading manifest file 'lvcache.egg-info/SOURCES.txt'
writing manifest file 'lvcache.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/lvcache
copying build/lib.linux-x86_64-2.7/lvcache/lvm.py -> build/bdist.linux-x86_64/egg/lvcache
copying build/lib.linux-x86_64-2.7/lvcache/cmd_status.py -> build/bdist.linux-x86_64/egg/lvcache
copying build/lib.linux-x86_64-2.7/lvcache/cmd_remove.py -> build/bdist.linux-x86_64/egg/lvcache
copying build/lib.linux-x86_64-2.7/lvcache/cmd_create.py -> build/bdist.linux-x86_64/egg/lvcache
copying build/lib.linux-x86_64-2.7/lvcache/cmd_list.py -> build/bdist.linux-x86_64/egg/lvcache
copying build/lib.linux-x86_64-2.7/lvcache/utils.py -> build/bdist.linux-x86_64/egg/lvcache
copying build/lib.linux-x86_64-2.7/lvcache/__init__.py -> build/bdist.linux-x86_64/egg/lvcache
copying build/lib.linux-x86_64-2.7/lvcache/main.py -> build/bdist.linux-x86_64/egg/lvcache
byte-compiling build/bdist.linux-x86_64/egg/lvcache/lvm.py to lvm.pyc
byte-compiling build/bdist.linux-x86_64/egg/lvcache/cmd_status.py to cmd_status.pyc
byte-compiling build/bdist.linux-x86_64/egg/lvcache/cmd_remove.py to cmd_remove.pyc
byte-compiling build/bdist.linux-x86_64/egg/lvcache/cmd_create.py to cmd_create.pyc
byte-compiling build/bdist.linux-x86_64/egg/lvcache/cmd_list.py to cmd_list.pyc
byte-compiling build/bdist.linux-x86_64/egg/lvcache/utils.py to utils.pyc
byte-compiling build/bdist.linux-x86_64/egg/lvcache/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/lvcache/main.py to main.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying lvcache.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying lvcache.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying lvcache.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying lvcache.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying lvcache.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying lvcache.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist/lvcache-1-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing lvcache-1-py2.7.egg
Copying lvcache-1-py2.7.egg to /usr/local/lib/python2.7/dist-packages
Adding lvcache 1 to easy-install.pth file
Installing lvcache script to /usr/local/bin

Installed /usr/local/lib/python2.7/dist-packages/lvcache-1-py2.7.egg
Processing dependencies for lvcache==1
Searching for sh
Reading https://pypi.python.org/simple/sh/
Best match: sh 1.09
Downloading https://pypi.python.org/packages/source/s/sh/sh-1.09.tar.gz#md5=b68a2f91de880dce042d4f03ec9e0f47
Processing sh-1.09.tar.gz
Writing /tmp/easy_install-gpvxxQ/sh-1.09/setup.cfg
Running sh-1.09/setup.py -q bdist_egg --dist-dir /tmp/easy_install-gpvxxQ/sh-1.09/egg-dist-tmp-_L2AkB
zip_safe flag not set; analyzing archive contents...
sh: module references __file__
sh: module references __path__
Adding sh 1.09 to easy-install.pth file

Installed /usr/local/lib/python2.7/dist-packages/sh-1.09-py2.7.egg
Searching for cliff
Reading https://pypi.python.org/simple/cliff/
Best match: cliff 1.8.0
Downloading https://pypi.python.org/packages/source/c/cliff/cliff-1.8.0.tar.gz#md5=4390eee272c8e4aefb15edb030700b8e
Processing cliff-1.8.0.tar.gz
Writing /tmp/easy_install-Oos_TX/cliff-1.8.0/setup.cfg
Running cliff-1.8.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-Oos_TX/cliff-1.8.0/egg-dist-tmp-eUNow6
Searching for pbr
Reading https://pypi.python.org/simple/pbr/
Best match: pbr 0.10.0
Downloading https://pypi.python.org/packages/source/p/pbr/pbr-0.10.0.tar.gz#md5=9e02dbfb5e49210c381fd4eea00cf7b7
Processing pbr-0.10.0.tar.gz
Writing /tmp/easy_install-Oos_TX/cliff-1.8.0/temp/easy_install-p4vf4C/pbr-0.10.0/setup.cfg
Running pbr-0.10.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-Oos_TX/cliff-1.8.0/temp/easy_install-p4vf4C/pbr-0.10.0/egg-dist-tmp-rCCZ15

Installed /tmp/easy_install-Oos_TX/cliff-1.8.0/pbr-0.10.0-py2.7.egg
Searching for pip
Reading https://pypi.python.org/simple/pip/
Best match: pip 1.5.6
Downloading https://pypi.python.org/packages/source/p/pip/pip-1.5.6.tar.gz#md5=01026f87978932060cc86c1dc527903e
Processing pip-1.5.6.tar.gz
Writing /tmp/easy_install-Oos_TX/cliff-1.8.0/temp/easy_install-D54p2X/pip-1.5.6/setup.cfg
Running pip-1.5.6/setup.py -q bdist_egg --dist-dir /tmp/easy_install-Oos_TX/cliff-1.8.0/temp/easy_install-D54p2X/pip-1.5.6/egg-dist-tmp-JRzkck
warning: no files found matching 'pip/cacert.pem'
warning: no files found matching '*.html' under directory 'docs'
warning: no previously-included files matching '*.rst' found under directory 'docs/_build'
no previously-included directories found matching 'docs/_build/_sources'

Installed /tmp/easy_install-Oos_TX/cliff-1.8.0/pip-1.5.6-py2.7.egg
Adding cliff 1.8.0 to easy-install.pth file

Installed /usr/local/lib/python2.7/dist-packages/cliff-1.8.0-py2.7.egg
Searching for stevedore>=0.14
Reading https://pypi.python.org/simple/stevedore/
Best match: stevedore 1.1.0
Downloading https://pypi.python.org/packages/source/s/stevedore/stevedore-1.1.0.tar.gz#md5=b7f30055c32410f8f9b6cf1b55bdc68a
Processing stevedore-1.1.0.tar.gz
Writing /tmp/easy_install-XE3BUz/stevedore-1.1.0/setup.cfg
Running stevedore-1.1.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-XE3BUz/stevedore-1.1.0/egg-dist-tmp-2yiHIG
Searching for pbr
Reading https://pypi.python.org/simple/pbr/
Best match: pbr 0.10.0
Downloading https://pypi.python.org/packages/source/p/pbr/pbr-0.10.0.tar.gz#md5=9e02dbfb5e49210c381fd4eea00cf7b7
Processing pbr-0.10.0.tar.gz
Writing /tmp/easy_install-XE3BUz/stevedore-1.1.0/temp/easy_install-u8LAV5/pbr-0.10.0/setup.cfg
Running pbr-0.10.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-XE3BUz/stevedore-1.1.0/temp/easy_install-u8LAV5/pbr-0.10.0/egg-dist-tmp-LN1eJx

Installed /tmp/easy_install-XE3BUz/stevedore-1.1.0/pbr-0.10.0-py2.7.egg
Searching for pip
Reading https://pypi.python.org/simple/pip/
Best match: pip 1.5.6
Downloading https://pypi.python.org/packages/source/p/pip/pip-1.5.6.tar.gz#md5=01026f87978932060cc86c1dc527903e
Processing pip-1.5.6.tar.gz
Writing /tmp/easy_install-XE3BUz/stevedore-1.1.0/temp/easy_install-QezNdp/pip-1.5.6/setup.cfg
Running pip-1.5.6/setup.py -q bdist_egg --dist-dir /tmp/easy_install-XE3BUz/stevedore-1.1.0/temp/easy_install-QezNdp/pip-1.5.6/egg-dist-tmp-MFa1JJ
warning: no files found matching 'pip/cacert.pem'
warning: no files found matching '*.html' under directory 'docs'
warning: no previously-included files matching '*.rst' found under directory 'docs/_build'
no previously-included directories found matching 'docs/_build/_sources'

Installed /tmp/easy_install-XE3BUz/stevedore-1.1.0/pip-1.5.6-py2.7.egg
Adding stevedore 1.1.0 to easy-install.pth file

Installed /usr/local/lib/python2.7/dist-packages/stevedore-1.1.0-py2.7.egg
Searching for pyparsing>=2.0.1
Reading https://pypi.python.org/simple/pyparsing/
Reading http://pyparsing.sourceforge.net/
Reading http://pyparsing.wikispaces.com/
Reading http://sourceforge.net/project/showfiles.php?group_id=97203
Reading http://sourceforge.net/projects/pyparsing
Best match: pyparsing 2.0.3
Downloading https://pypi.python.org/packages/source/p/pyparsing/pyparsing-2.0.3.zip#md5=0a5ec41bb650aed802751a311b5d820d
Processing pyparsing-2.0.3.zip
Writing /tmp/easy_install-9z5K_p/pyparsing-2.0.3/setup.cfg
Running pyparsing-2.0.3/setup.py -q bdist_egg --dist-dir /tmp/easy_install-9z5K_p/pyparsing-2.0.3/egg-dist-tmp-zRoyuc
zip_safe flag not set; analyzing archive contents...
pyparsing: module MAY be using inspect.stack
Adding pyparsing 2.0.3 to easy-install.pth file

Installed /usr/local/lib/python2.7/dist-packages/pyparsing-2.0.3-py2.7.egg
Searching for PrettyTable>=0.7,<0.8
Reading https://pypi.python.org/simple/PrettyTable/
Best match: prettytable 0.7.2
Downloading https://pypi.python.org/packages/source/P/PrettyTable/prettytable-0.7.2.zip#md5=0c1361104caff8b09f220748f9d69899
Processing prettytable-0.7.2.zip
Writing /tmp/easy_install-SzJRow/prettytable-0.7.2/setup.cfg
Running prettytable-0.7.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-SzJRow/prettytable-0.7.2/egg-dist-tmp-kvjii0
zip_safe flag not set; analyzing archive contents...
Adding prettytable 0.7.2 to easy-install.pth file

Installed /usr/local/lib/python2.7/dist-packages/prettytable-0.7.2-py2.7.egg
Searching for cmd2>=0.6.7
Reading https://pypi.python.org/simple/cmd2/
Best match: cmd2 0.6.7
Downloading https://pypi.python.org/packages/2.7/c/cmd2/cmd2-0.6.7-py2.7.egg#md5=10adeed6fb33ae86d768b682f828fbbf
Processing cmd2-0.6.7-py2.7.egg
Moving cmd2-0.6.7-py2.7.egg to /usr/local/lib/python2.7/dist-packages
Adding cmd2 0.6.7 to easy-install.pth file

Installed /usr/local/lib/python2.7/dist-packages/cmd2-0.6.7-py2.7.egg
Searching for pbr>=0.6,!=0.7,<1.0
Reading https://pypi.python.org/simple/pbr/
Best match: pbr 0.10.0
Downloading https://pypi.python.org/packages/source/p/pbr/pbr-0.10.0.tar.gz#md5=9e02dbfb5e49210c381fd4eea00cf7b7
Processing pbr-0.10.0.tar.gz
Writing /tmp/easy_install-lulQD3/pbr-0.10.0/setup.cfg
Running pbr-0.10.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-lulQD3/pbr-0.10.0/egg-dist-tmp-PtgLxE
Adding pbr 0.10.0 to easy-install.pth file

Installed /usr/local/lib/python2.7/dist-packages/pbr-0.10.0-py2.7.egg
Searching for pip
Reading https://pypi.python.org/simple/pip/
Best match: pip 1.5.6
Downloading https://pypi.python.org/packages/source/p/pip/pip-1.5.6.tar.gz#md5=01026f87978932060cc86c1dc527903e
Processing pip-1.5.6.tar.gz
Writing /tmp/easy_install-Pjv1rZ/pip-1.5.6/setup.cfg
Running pip-1.5.6/setup.py -q bdist_egg --dist-dir /tmp/easy_install-Pjv1rZ/pip-1.5.6/egg-dist-tmp-XI00kU
warning: no files found matching 'pip/cacert.pem'
warning: no files found matching '*.html' under directory 'docs'
warning: no previously-included files matching '*.rst' found under directory 'docs/_build'
no previously-included directories found matching 'docs/_build/_sources'
Adding pip 1.5.6 to easy-install.pth file
Traceback (most recent call last):
  File "setup.py", line 22, in <module>
    'list = lvcache.cmd_list:List',
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 393, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 617, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 668, in install_item
    self.process_distribution(spec, dist, deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 716, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 631, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 874, in best_match
    return self.obtain(req, installer)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 886, in obtain
    return installer(requirement)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 636, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 668, in install_item
    self.process_distribution(spec, dist, deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 693, in process_distribution
    self.install_egg_scripts(dist)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 571, in install_egg_scripts
    self.install_wrapper_scripts(dist)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 769, in install_wrapper_scripts
    for args in get_script_args(dist):
  File "/tmp/easy_install-lulQD3/pbr-0.10.0/pbr/packaging.py", line 512, in override_get_script_args
AttributeError: 'NoneType' object has no attribute 'get_script_header'
```

Subsequent try:
````
# python setup.py --help-commands
Traceback (most recent call last):
  File "setup.py", line 22, in <module>
    'list = lvcache.cmd_list:List',
  File "/usr/lib/python2.7/distutils/core.py", line 137, in setup
    ok = dist.parse_command_line()
  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 273, in parse_command_line
    result = _Distribution.parse_command_line(self)
  File "/usr/lib/python2.7/distutils/dist.py", line 464, in parse_command_line
    if self.handle_display_options(option_order):
  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 636, in handle_display_options
    return _Distribution.handle_display_options(self, option_order)
  File "/usr/lib/python2.7/distutils/dist.py", line 669, in handle_display_options
    self.print_commands()
  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 396, in print_commands
    cmdclass = ep.load(False) # don't require extras, we're not running
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2190, in load
    ['__name__'])
  File "/usr/local/lib/python2.7/dist-packages/pbr-0.10.0-py2.7.egg/pbr/testr_command.py", line 47, in <module>
    from testrepository import commands
ImportError: No module named testrepository
root@deb:/home/bence/stuff/lvcache-master# python setup.py --help-commands
Traceback (most recent call last):
  File "setup.py", line 22, in <module>
    'list = lvcache.cmd_list:List',
  File "/usr/lib/python2.7/distutils/core.py", line 137, in setup
    ok = dist.parse_command_line()
  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 273, in parse_command_line
    result = _Distribution.parse_command_line(self)
  File "/usr/lib/python2.7/distutils/dist.py", line 464, in parse_command_line
    if self.handle_display_options(option_order):
  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 636, in handle_display_options
    return _Distribution.handle_display_options(self, option_order)
  File "/usr/lib/python2.7/distutils/dist.py", line 669, in handle_display_options
    self.print_commands()
  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 396, in print_commands
    cmdclass = ep.load(False) # don't require extras, we're not running
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2190, in load
    ['__name__'])
  File "/usr/local/lib/python2.7/dist-packages/pbr-0.10.0-py2.7.egg/pbr/testr_command.py", line 47, in <module>
    from testrepository import commands
ImportError: No module named testrepository

**Comment by larsks** [comment]
I am not able to reproduce this problem. With python 2.7 on my system this installs without a problem.  Consider running `pip install .` instead of `python setup.py ...` and see if that helps.
